### ISSUE TITLE
framework-spl folder is modified by PlatformIO when it starts

### ISSUE THREAD

**Issue by maxicuevas** [maxgerhardt/pio-gd32f130c6#2]
I have noticed that the folder framework-spl is modified when PlatformIO starts. 

1. Unpack the framework-spl.zip in the packages folder as you pointed out
The directory structure is as expected:
packages/
| - framework-spl/
| |--  gd32/
| |--  platformio/
| |--  stm32/
| |--  package.json 

2. Start PlatformIO
The folder gd32 is removed by PlatformIO from framework-spl

I am running PlatformIO (Core 5.0.1 Home 3.3.0) under VS Code (1.49.1) with a Mac (OS Sierra 10.12.6)

Do you have any suggestions?
Thank you in advance!

**Comment by maxgerhardt** [comment]
Huh, I haven't noticed that beavior... shouldn't be doing it unless it's trying too update the `framework-spl` package. 

But yes there's a clean fix for it. I'll just have to publish the `framework-spl` package in the PlatformIO registry and then use it by including `platform_packages = framework-spl@...`. I'll look into it.

**Comment by maxicuevas** [comment]
Hi Max,
thanks a lot for your prompt answer!

**Comment by maxgerhardt** [comment]
Just as a heads up, I'm on this but didn't find the time yet

**Comment by maxicuevas** [comment]
Fine! thank you!
I observed the same behaviour if:
a.  Start PlatformIO
b. After Platformio is running, I unpack the framework-spl.zip in the packages folder  
c. When I click on build, then gd32 is removed by PlatformIO from framework-spl

**Comment by ghost** [comment]
Hi Max,
I’m facing exactly the same problem as Maxi. Did you have a chance to have a look at it?  Can I check out the fixed version now?
Thanks for the quick help !
Nice work by the way 😃
Nicolas

**Comment by maxgerhardt** [comment]
Thanks for pinging me, I've just 

```
>pio package publish --notify framework-spl-2.10300.0.tar.gz
The package has been accepted for moderation. We will notify you on email when process it.
```
published the package which should be available in the PIO trusted registry when it's approved in 1-2 days. Then this project can be pointed at my official package, which should eliminate those problems.

**Comment by maxgerhardt** [comment]
Oh that was fast.

>Congrats, maxgerhardt!
>
>A new version of the package framework-spl (2.10300.0) was published at 2020-10-22 12:37:05 from 87.XXX.XXX.XXX. 

Will update project soon.

**Comment by EFeru** [comment]
Does this mean that the GD32 chip is now supported by Platformio and we don't need to do the steps of copying folders etc? 
If yes, what do we need to specify in platformio.ini to use the chip?

**Comment by maxgerhardt** [comment]
No what I did was publish the package under my PIO account; So the a `maxgerhardt/framework-spl` package of version `2.10300.0` is now in the PIO trusted registry, and that should be referencable in the `platform_packages` now, thus eliminating the need to manually copy the `framework-spl.zip` package. I'll figure out what exact `platform_packages` command works and update the projects.

**Comment by maxgerhardt** [comment]
Closed by https://github.com/maxgerhardt/pio-gd32f130c6/commit/21e8042cf8421686c4bb0ce1dee4dd7b088cae55. Please see update `README.md`. If there are errors (I have tested it on my local machine by removing my old `framework-spl` folder in `~/.platformio/packages/`, then building the project, which installs my new version from the global registry), please reopen.

The related project https://github.com/maxgerhardt/pio-gd32f103 was updated as well.
